server:
  port: 8084
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/spring-boot?useUnicode=true&characterEncoding=UTF-8&zeroDateTimeBehavior=convertToNull
    username: root
    password: root
    driver-class-name: com.mysql.jdbc.Driver
    type: com.zaxxer.hikari.HikariDataSource
    hikari:
          connection-test-query: select 1 from dual
          connection-timeout: 30000
          idle-timeout: 60000
          max-lifetime: 1800000
          maximum-pool-size: 50
          minimum-idle: 50
  redis:
       database: 0
       host: localhost
       port: 6379
       password: root
       timeout: 0
       pool:
          max-active: 20
          min-idle: 5
          max-idle: 10
          max-wait: -1
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8

project:
  version: @project.version@
  buildTime: @project.build.time@
  format: @maven.build.timestamp.format@
mybatis:
    type-aliases-package: com.zero.po
    mapper-locations: classpath:com.zero.dao/*.xml
mapper:
    mappers:
        - com.zero.conf.MyMapper
    not-empty: false
    identity: MYSQL
pagehelper:
    helperDialect: mysql
    reasonable: true
    supportMethodsArguments: true
    params: count=countSql
http:
    scheme: http
    hostname: localhost
    port: 8081
passwordHash:
    algorithmName: md5
    hashIterations: 1
logging:
  level:
    com.zero: debug
    org.springframework.web: debug
    springframework.transaction: debug
    org.mybatis: debug
