server:
  port: 8080
spring:
  activemq:
    user: admin
    password: admin
    broker-url: tcp://localhost:61616?jms.prefetchPolicy.all=10&jms.optimizeAcknowledge=true
    in-memory: true
    pool:
      enabled: false
    packages:
      trust-all: true
logging:
  level:
    com.zero: debug
    org.springframework.web: debug
    springframework.transaction: debug
