server:
  port: 8081
spring:
  dubbo:
    application:
      name: dubbo-server
    registry:
      address: zookeeper://www.hiyzx.cn:2181
    protocol:
      name: dubbo
      port: 20881
    scan: com.zero.product.service.impl
