spring:
  datasource:
    url: jdbc:mysql://www.hiyzx.cn:3306/elastic-job?useUnicode=true&characterEncoding=UTF-8&zeroDateTimeBehavior=convertToNull
    username: root
    password: yzx362311
    driver-class-name: com.mysql.jdbc.Driver
server:
  port: 8080

elasticJob:
  regCenter:
    serverList: 127.0.0.1:2181
    namespace: elastic-job
  firstJob:
    cron: 0 * * * * ?
    shardingTotalCount: 1
    shardingItemParameters: 0=Beijing
    failover: true
  secondJob:
    cron: 0 1 * * * ?
    shardingTotalCount: 1
    shardingItemParameters: 0=Shanghai
    failover: true
logging:
  level:
    org.apache.zookeeper: INFO
    org.springframework.beans.factory.support: INFO

