server:
  port: 8085
spring:
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
  resources:
    add-mappings: false
  mvc:
    throw-exception-if-no-handler-found: true
logging:
  level:
    com.zero: debug
    org.springframework.web: debug
    springframework.transaction: debug
example:
  service:
    enabled: true
    prefix: 111
    suffix: 222
snowflake:
  enable: true
  dataCenter: 1
  serviceId: 1
  zkUrl: 127.0.0.1:2181