server:
  port: 8080
spring:
  redis:
       database: 0
       host: www.hiyzx.cn
       port: 6379
       password: yzx362311
       timeout: 0
       pool:
          max-active: 20
          min-idle: 5
          max-idle: 10
          max-wait: -1
logging:
  level:
    com.zero: info
