server:
  port: 8080
spring:
  redis:
       database: 0
       host: 192.168.1.231
       port: 6381
       password: zHx3bQBDVuSsAE80A2jA
       timeout: 0
       pool:
          max-active: 20
          min-idle: 5
          max-idle: 10
          max-wait: -1
logging:
  level:
    com.zero: info
