server:
  port: 8080
spring:
  redis:
       database: 0
       host: www.hiyzx.cn
       port: 6379
       password: 123456
       timeout: 10000
       jedis:
         pool:
           max-idle: 20
           min-idle: 5
           max-wait:
logging:
  level:
    com.zero: info
